services:
  prod:
    image: tons/hello-db:${IMAGE_TAG:-latest}
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${PROD_DOMAIN}`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
    depends_on:
      database:
        condition: service_healthy

  traefik-init:
    image: alpine:3.22
    volumes:
      - cert:/cert:rw
      - ./init-cert.sh:/init-cert.sh:ro
    command: [ "/init-cert.sh" ]

  traefik:
    image: traefik:v3.0
    depends_on:
      traefik-init:
        condition: service_completed_successfully
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/cert/acme.json"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - cert:/cert:rw

volumes:
  cert: {}
